"""Init

Revision ID: ae58ec5dfe8f
Revises:
Create Date: 2023-04-13 23:35:26.495532

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ae58ec5dfe8f"
down_revision = None
branch_labels = None
depends_on = None


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index("ix_user_email", table_name="user")
    # op.drop_index("ix_user_id", table_name="user")
    # op.drop_index("ix_user_username", table_name="user")
    # op.drop_table("user")
    # op.drop_index("ix_todo_id", table_name="todo")
    # op.drop_table("todo")
    # ### end Alembic commands ###


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    #     "todo",
    #     sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    #     sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
    #     sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    #     sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
    #     sa.Column("complete", sa.BOOLEAN(), autoincrement=False, nullable=True),
    #     sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
    #     sa.ForeignKeyConstraint(["owner_id"], ["user.id"], name="todo_owner_id_fkey"),
    #     sa.PrimaryKeyConstraint("id", name="todo_pkey"),
    # )
    # op.create_index("ix_todo_id", "todo", ["id"], unique=False)
    # op.create_table(
    #     "user",
    #     sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    #     sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
    #     sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True),
    #     sa.Column("firstname", sa.VARCHAR(), autoincrement=False, nullable=True),
    #     sa.Column("lastname", sa.VARCHAR(), autoincrement=False, nullable=True),
    #     sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True),
    #     sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    #     sa.PrimaryKeyConstraint("id", name="user_pkey"),
    # )
    # op.create_index("ix_user_username", "user", ["username"], unique=False)
    # op.create_index("ix_user_id", "user", ["id"], unique=False)
    # op.create_index("ix_user_email", "user", ["email"], unique=False)
    # ### end Alembic commands ###
